### ISSUE TITLE
2019.1 DefaultReflector could not be found

### ISSUE THREAD

**Issue by ARKAIKGD** [evasiongames/gameflow#102]
Hi,
After upgrading gameflow to v1.2 there is an error that states: 
![image](https://user-images.githubusercontent.com/8311531/56619478-843a2a80-661d-11e9-986c-f9a0bf264cc6.png)
![image](https://user-images.githubusercontent.com/8311531/56619644-2eb24d80-661e-11e9-9749-52abd627b597.png)

**Comment by evasiongames** [comment]
It seems like the GameFlow.dll (where the RuntimeReflection type is defined) have not been imported in your project. Did you also update your Unity from 2018.3 (or lower) to 2019.1 before updating to v1.2? If you did, please check the [Version].txt in the /GameFlow folder for instructions. Please try also to import GameFlow in a new project just to confirm that it was a bad import.

**Comment by evasiongames** [comment]
I found what the problem is. You probably have the Scripting Runtime Version set to .Net 3.5 Equivalent (which is deprecated) and GameFlow requires .Net 4.x. This option is in the Player pane of the Project Settings:
![Screen Shot 2019-04-24 at 07 20 14](https://user-images.githubusercontent.com/7121057/56634328-e452c000-6661-11e9-996a-43bf3ac2091b.png)

**Comment by ARKAIKGD** [comment]
Yes, that was the issue its working fine now thanks for your help
