### ISSUE TITLE
Trouble running snippets in editmode

### ISSUE THREAD

**Issue by Flavelius** [evasiongames/gameflow#52]
Hi, as the other issue states, this really needs some tutorials or documentation.
I'm trying to run a program in editmode, but can't quite figure out how to. 
After some time exploring i found that one of the rightclick menus has an 'execute' entry that seems to do that.
It seems, officially, that macros are meant to be used that way, but they only allow 'call method' as action which is not very useful. 
When i create a program and change the type to macro afterwards (not sure if intended, but it's possible..) it seems to work, but only the first time.
hitting the hotkey for the second time repeats the program infinitely (bug?). (I used the 03-Log Message example scene program to test this)

Edit: this even happens if i don't set the type to macro and use the execute context menu
Edit 2: and it cannot be stopped, apart from destroying the gameobject or the component
Edit 3: My bad, looks like this is related to the break condition. The points about the inabillity to stop loops or the need to convert to macro otherwise are still valid though

Edit4: Sorry, i just noticed that i had filtered out most actions in the macro-action-add-dialog..
the ability to stop loops/execution manually would still be nice though

**Comment by evasiongames** [comment]
Not really a bug. The problem is that Example 03 (Log Message) was not created to be executed in Edit mode and because of that it assumes an initial value of zero for the \<Counter\> variable.

So, what's happening? After the first execution, the value of the variable will be 3 because in Edit mode value are not restored like in Play mode. So, the next time you execute, the program will enter an infinite loop because the If Variable Value (Is Equal to 3) will never be matched as first thing in the Loop is an Increment Variable Value action which makes it 4.

So how do you fix it? Just insert a Set Variable Value as first action in the program to set the value of \<Counter\> to zero. That way you will avoid the infinite loop.

> the ability to stop loops/execution manually would still be nice though

Agreed. I will add an issue for that and do my best to have it available in the next update.
